Implement watching extra files from CLI
Pylons/hupper pull request #28
Opened 2017-05-22 19:22 UTC by j-carl

Implement watching extra files from CLI #18

2017-05-22 20:39 UTC, mmerickel requested changes
Please rebase on master and add your name to `CONTRIBUTORS.txt`.

2017-05-22 20:39 UTC, mmerickel commented on src/hupper/cli.py
> +        **{"alter_sys": True, "run_name": "__main__"})
Please modify this to use regular function kwargs - `alter_sys=True, run_name='__main__'`.

2017-05-23 21:55 UTC, j-carl commented on src/hupper/cli.py
> +        **{"alter_sys": True, "run_name": "__main__"})
Made the changes

2017-05-23 21:58 UTC, mmerickel approved these changes

2017-05-23 21:59 UTC, merged

2017-05-23 21:59 UTC, mmerickel commented
Thanks @j-carl !